### ISSUE TITLE
Errors importing custom component after updating to 0.2.4

### ISSUE THREAD

**Issue by jimcj1301** [rsnodgrass/hass-adtpulse#30]
@rlippmann - Errors importing custom component after updating to 0.2.4

I attempted to remove and re-install after updating and now when I check YAML before restarting it returns the error below. This prevents the ability to reboot. Let me know if there is something you recommend I try to help.  
-----
Configuration invalid!
Component error: adtpulse - Exception importing custom_components.adtpulse
-----

```
Logger: homeassistant.loader
Source: loader.py:813
First occurred: 7:46:56 PM (4 occurrences)
Last logged: 8:59:35 PM

Unexpected exception importing component custom_components.adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/adtpulse/__init__.py", line 178
    except Exception as e
                         ^
SyntaxError: expected ':'
```

**Comment by jimcj1301** [comment]
Fixed SyntaxError and integration installed and loads.

Just getting an authentication error now it seems.


`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/adtpulse/__init__.py:58
Integration: ADT Pulse (documentation, issues)
First occurred: 10:00:11 PM (1 occurrences)
Last logged: 10:00:11 PM

Error setting up entry ADT: **MYLOGIN** for adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/adtpulse/__init__.py", line 58, in async_setup_entry
    adtpulse = await hass.async_add_executor_job(PyADTPulse,entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD], entry.data[CONF_FINGERPRINT], entry.data[CONF_HOSTNAME],ADT_DEFAULT_HTTP_HEADERS, None, True, polling, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyadtpulse/__init__.py", line 167, in __init__
    self.login()
  File "/usr/local/lib/python3.10/site-packages/pyadtpulse/__init__.py", line 505, in login
    raise AuthenticationException(self._username)
pyadtpulse.util.AuthenticationException: **MYLOGIN**
`

**Comment by rlippmann** [comment]
Yeah, the merge is a mess. It shouldn’t be running the login in the executor. 

Can you rollback?

**Comment by jimcj1301** [comment]
Yeah, I was able to rollback and clean up my configuration. Back to normal.

Thanks again for the support!

**Comment by rlippmann** [comment]
It looks like the old code was in the last release.  I did a new release, but I still see some problems.
